### ISSUE TITLE
DBCs fail to load on startup

### ISSUE THREAD

**Issue by Razfury** [Sandshroud/Sandshroud-Prodigy#1]
Compiled everything fine went to boot up the worldserver and got the major error / warning about dbcs even though I have the correct path and the dbc folder.

I do have the DBC folder in the right place and the configs are correct.

**Comment by Thetruecrow** [comment]
Sorry for the late response, I didn't get a notification for this issue.

Did you generate your DBC files using the extractor from the project or did you use ones you had previously? Our generator will create a custom DBC file to store bounding information of creature models necessary for some functionality.

I lost my HDDs with all my clients backed up, so at the moment I am waiting on a p2p transfer to go through for the WOTLK client. Once that is done I will have the DBC and map files extracted myself and will check first hand.

Edit:
Extracted DBCs and maps perfectly and was able to log in, if you want the custom DBC file to use without having to re-extract you can download it here:
http://www.mediafire.com/file/zspthdt7m6x4gda/CreatureBoundInformation.dbc

**Comment by Razfury** [comment]
That was the problem I was using my own dbcs not extracted ones guess I should've tried that haha - thanks!
