### ISSUE TITLE
[CRASH with DUMP] Attacking or monster Attacking

### ISSUE THREAD

**Issue by Razfury** [Sandshroud/Sandshroud-Prodigy#2]
Anytime you attack or another creature attacks you the server crashes.

crashdump[RELWITHDEBINFO]: https://ufile.io/mn7xa

@Thetruecrow

**Comment by Thetruecrow** [comment]
I can't use dump files without also having the debug libraries to point the compiler to.

Can I get a bit more info, like are you compiling with the script engine, are you utilizing the collision option or pathfinding, what maps are you using and if you want to just open the dump yourself and take a printscreen and upload it so I can see what line the core is crashing at I can try and resolve it.

That being said I haven't experienced this issue myself.

**Comment by Razfury** [comment]
yes, I am compiling with the script engine - i'm not using collision or pathfinding (using trinitycore maps)

SS:
![hs-world-1](https://user-images.githubusercontent.com/28716035/43832658-222bfdb8-9ad6-11e8-80e0-596ae809e980.png)
![hs-world-2](https://user-images.githubusercontent.com/28716035/43832661-254f9b94-9ad6-11e8-8508-5e67af95d79b.png)

**Comment by Razfury** [comment]
I setup lacrimi wrong and fixed it everything works now!
