### ISSUE TITLE
Some spell visuals are missing

### ISSUE THREAD

**Issue by Razfury** [Sandshroud/Sandshroud-Prodigy#3]
@Thetruecrow 
Problem: Spells are missing visuals.
Reproduce:
Step 1: Create a human paladin 
Step 2: cast seal of rightenouss notice no spell visual, next cast holy light notice no spell visual effect

Step 3: create a human mage
Step 4: cast fireball at a monster notice no spell visual, next cast frost armor notice no spell visual effect

I'm using dbc. maps no collision or mmaps. I'm using Lacrimi.
Spell visuals like flamestrike or dragon's breath work it's weird.

**Comment by Thetruecrow** [comment]
I noticed this as well, I will look into fixing it soon hopefully, but my time is a little thin.

**Comment by Thetruecrow** [comment]
Resolved with commit d397360f902280e14aa589434a3ad34ab4f4efb1
