### ISSUE TITLE
Spell procs don't work?

### ISSUE THREAD

**Issue by Razfury** [Sandshroud/Sandshroud-Prodigy#4]
Lacrimi has spell procs and effects however they don't work (proc) im assuming this is a core issue

Spec into fire tree with Ignite and Impact and hit training dummies in stormwind & notice that they don't proc when you do what the ability says. Think this impacts all procs?
@Thetruecrow

**Comment by Thetruecrow** [comment]
In this specific case it's only because Ignite does not have the proper spell to trigger linked to it's spell entry.

I'm sure there are tons of other spells that also suffer since from the beginning this core was never set up to properly emulate the functionality of Wotlk.

**Comment by Thetruecrow** [comment]
Fixed in 5584b321030faf1122c306024991b48621d4d631
